### ISSUE TITLE
[BUG] There is memory leak

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#385]
### Describe the bug

If train yolox model for long epochs with multi-gpu, memory occupation of 0 gpu gradually increase during training.
At the end, it occurs OOM error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run with large dataset and long epochs. for example:
```
python train.py\
  --data config/coco2017.yaml\
  --augmentation config/yolox/augmentation.yaml\
  --model config/yolox.yaml\
  --training config/training.yaml\
  --logging config/logging.yaml\
  --environment config/environment.yaml
```

### System Info

```shell
Current dev branch
```

**Comment by illian01** [comment]
@aychun
I opened this issue which you reported through other channel.
If there is more information about this issue, please leave at here. 👍

**Comment by aychun** [comment]
@illian01 
I figured it would be better to just share the `hparams.yaml`and `result.log` files in the outputs directory here. I also attached a screenshot of the gpu utilization during the training. Note that the log file is based on the UTC time while the screenshot displays KST (UTC+9).

GPU info: NVIDIA GeForce RTX 2080 Ti (X4)

<img width="829" alt="Screenshot 2024-03-27 at 11 56 06 PM" src="https://github.com/Nota-NetsPresso/netspresso-trainer/assets/85460898/ca94cfc8-f6e0-4485-b1f3-95962c7675f7">
<br/><br/>
 
[`result.log`](https://github.com/Nota-NetsPresso/netspresso-trainer/files/14775235/result.log)

`hparams.yaml` (looks like github doesn't allow attaching yaml files for some reason)

```
data:
  name: traffic_sign_yolo
  task: detection
  format: local
  path:
    root: data/traffic-sign
    train:
      image: images/train
      label: labels/train
    valid:
      image: images/valid
      label: labels/valid
    test:
      image: null
      label: null
    pattern:
      image: null
      label: null
  id_mapping:
  - prohibitory
  - danger
  - mandatory
  - other
  pallete: null
augmentation:
  img_size: 512
  train:
    transforms:
    - name: resize
      size:
      - 512
      - 512
      interpolation: bilinear
      max_size: null
  inference:
    transforms:
    - name: resize
      size:
      - 512
      - 512
      interpolation: bilinear
      max_size: null
model:
  task: detection
  name: yolox_fastest-tmp
  checkpoint:
    use_pretrained: false
    load_head: false
    path: null
    fx_model_path: null
    optimizer_path: null
  freeze_backbone: false
  architecture:
    full: null
    backbone:
      name: cspdarknet
      params:
        dep_mul: 0.33
        wid_mul: 0.5
        act_type: silu
      stage_params: null
    neck:
      name: yolopafpn
      params:
        dep_mul: 0.33
        act_type: silu
    head:
      name: anchor_free_decoupled_head
      params:
        act_type: silu
        score_thresh: 0.7
        nms_thresh: 0.45
        class_agnostic: false
  losses:
  - criterion: yolox_loss
    weight: null
  single_task_model: false
training:
  epochs: 800
  batch_size: 16
  optimizer:
    name: adamw
    lr: 6.0e-05
    betas:
    - 0.9
    - 0.999
    weight_decay: 0.0005
  scheduler:
    name: cosine_no_sgdr
    warmup_epochs: 5
    warmup_bias_lr: 1.0e-05
    min_lr: 0.0
logging:
  project_id: null
  output_dir: ./outputs
  tensorboard: true
  csv: false
  image: true
  stdout: true
  save_optimizer_state: true
  validation_epoch: 10
  save_checkpoint_epoch: 10
environment:
  seed: 1
  num_workers: 8
  gpus: 0,1,2,3
distributed: true
world_size: 4
rank: 0
```
